# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6c2a69115de4dffb67f46b01170de31e0f265e4d076611d5338df122b76b1e9ea8dd4093e4d1f94561c52f40a8a8a2a39c05c862f668465036828d3df9d7abf4

test:
  secret_key_base: 795f8b8dd8a5909c6f9c70c45457cb2c7190db60cbce7611b3bb7e7d92efaefe4237a55c40342d1be29ed384cb5470ac93079b06f9b282ad032c7e6602c5d314

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
